site_name: Quantreo
site_url: https://docs.quantreo.com/
use_directory_urls: true
site_description: A faster way to build quantitative features, targets, and alternative bars in Python. Powered by Numba. Whether your goal is alpha research, backtesting, or production-ready model development, Quantreo offers a consistent and modular workflow.

theme:
  name: material
  custom_dir: overrides
  logo: assets/figures/quantreo_logo.png
  favicon: assets/figures/quantreo_icon.png
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    #- content.tabs.link
    - content.tabs
    - content.code.copy
    - content.code.annotation
    - content.icon
    - content.meta
    - navigation.footer




  language: en
  palette:
    - scheme: slate

nav:
  - Home: index.md

  - Documentation:
      - Data Aggregation:
          - Get Started: data-aggregation/Get-Started.md
          - Bar Building: data-aggregation/bar-building.md
          - Bar Metrics: data-aggregation/bar-metrics.md

      - Features Engineering:
          - Get Started: features-engineering/Get-Started.md
          - Candle Features: features-engineering/candle.md
          - Market Regime: features-engineering/market-regime.md
          - Math Functions: features-engineering/math.md
          - Transformations: features-engineering/transformation.md
          - Trend Features: features-engineering/trend.md
          - Volatility Estimators: features-engineering/volatility.md

      - Target Engineering:
          - Get Started: target-engineering/Get-started.md
          - Directional Targets: target-engineering/directional.md
          - Event-Based Targets: target-engineering/event-based.md
          - Magnitude Targets: target-engineering/magnitude.md

  - Tutorials:
      - Get Started:
        - Quantreo for Beginners: tutorials/Quantreo-for-beginners.md
      - Data Aggregation Tutorials:
          - Bar Building: tutorials/data-aggregation-bar-building.ipynb
          - Bar Metrics: tutorials/data-aggregation-bar-metrics.ipynb
      - Features Engineering Tutorials:
          - Candle Features: tutorials/features-engineering-candle.ipynb
          - Market Regime: tutorials/features-engineering-market-regime.ipynb
          - Math Functions: tutorials/features-engineering-math.ipynb
          - Transformations: tutorials/features-engineering-transformation.ipynb
          - Trend Features: tutorials/features-engineering-trend.ipynb
          - Volatility Estimators: tutorials/features-engineering-volatility.ipynb
      - Target Engineering Tutorials:
          - Directional Targets: tutorials/target-engineering-directional.ipynb
          - Event-Based Targets: tutorials/target-engineering-event-based.ipynb
          - Magnitude Targets: tutorials/target-engineering-magnitude.ipynb

  - Applications:
      - Meta-Labeling: tutorials/tutorial-meta-labeling.ipynb
      - Multi-Asset Feature Engineering: tutorials/tutorial-multi-asset-feature-engineering-in-financial-ml.ipynb
      - PCA in Trading: tutorials/tutorial-pca-in-trading.ipynb

  - Troubleshooting:
      - troubleshooting/troubleshooting.md

  - GitHub: https://github.com/Quantreo/quantreo




plugins:
  - social
  - search
  - mkdocs-jupyter


extra:
  base: ''
  text: Roboto
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Quantreo/quantreo
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@quantreo
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lucas-inglese-75574817b/


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
        alternate_style: true

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 2

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
  - assets/custom.js

extra_css:
  - stylesheets/custom.css

copyright: |
  &copy; 2025 <a href="https://github.com/"  target="_blank" rel="noopener">Quantreo