site_name: QUANTREO
site_url: https://docs.quantreo.com/
use_directory_urls: true

theme:
  name: material
  custom_dir: overrides
  logo: assets/figures/quantreo_icon.png
  favicon: assets/figures/quantreo_icon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer



  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent: lime

    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      accent: teal


plugins:
  - social
  - search
  - mkdocs-jupyter


extra:
  base: ''
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Quantreo
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@quantreo
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lucas-inglese-75574817b/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 2

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
  - assets/custom.js

extra_css:
  - stylesheets/custom.css

copyright: |
  &copy; 2025 <a href="https://github.com/"  target="_blank" rel="noopener">Quantreo