site_name: Quantreo
site_url: https://www.quantreo.com
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy


  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: teal
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: lime


plugins:
  - social
  - search


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Quantreo
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@quantreo
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lucas-inglese-75574817b/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 2

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

copyright: |
  &copy; 2025 <a href="https://github.com/"  target="_blank" rel="noopener">Quantreo