name: Quantreo CI

on:
  push:
    branches: [ modify-doc ]
  pull_request:
    branches: [ modify-doc ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install pytest pytest-cov ruff black

      - name: Run tests with coverage
        run: pytest --cov=quantreo --cov-report=term-missing -v --maxfail=1 --disable-warnings
